#!/usr/bin/env bash

pid_file="/var/run/myscript.pid"

# Function to handle SIGTERM signal
terminate() {
    echo "I hate the kill command"
    cleanup
    exit 0
}

# Function to handle SIGINT signal
interrupt() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit() {
    echo "Y U quit me?!"
    cleanup
    exit 0
}

# Function to handle cleanup tasks
cleanup() {
    echo "Cleaning up..."
    [ -e "$pid_file" ] && rm "$pid_file"
}

# Register signal handlers
trap 'terminate' SIGTERM
trap 'interrupt' SIGINT
trap 'quit' SIGQUIT

# Save PID to file
echo $$ > "$pid_file"

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
