#!/usr/bin/env bash
# a script that displays 1-100
# displays fizzbuzzwhen the number is multiple of 3 & 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# else display number in list format

for ((i=1; i<=100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
