#!/usr/bin/env bash
# a script that displays the content of the file /etc/passwd

while IFS=: read -r username _ userid _ _ home_directory _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home_directory"
done < /etc/passwd
