#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd,
# using the while loop + IFS

while IFS=: read -r username password userid groupid info home_directory shell;
do
    echo "The user $username is part of the $groupid gang,
    lives in $home_directory and rides $shell."
    echo "USER ID's place is protected by the passcode $password,
    more info about the user here: $info"
done < /etc/passwd
