#!/usr/bin/env bash
# a script that displays the time 12hr and 59min

# Initializing variables
hours=0

# Using a while loop to iterate over hours
while [ $hours -le 12 ]
do
    minutes=1

    # Using a while loop to iterate over minutes
    while [ $minutes -le 59 ]
    do
        # Formatting hours and minutes
        formatted_hours=$(printf "%02d" $hours)
        formatted_minutes=$(printf "%02d" $minutes)

        # Displaying time
        echo "$formatted_hours:$formatted_minutes"

        ((minutes++))
    done

    ((hours++))
done | head -n 70
