#!/usr/bin/env bash
# a script that displays the time 12hr and 59min

# Initializing variables
hour=0

while [ $hour -lt 12 ]
do
    echo "Hour: $hour"

    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done
