#!/usr/bin/env bash
# A Bash script that displays all active IPv4 IPs on the machine it’s executed

# Check if the script is run with sudo/root privileges
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root. Use sudo."
    exit 1
fi

# Display active IPv4 addresses using ifconfig
ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | awk '!/127.0.0.1/ {print}'

